language: d
dist: trusty
sudo: true

matrix:
  include:
    - d: dmd-nightly
      script: dub run --root mir-integration && dub run --build=unittest -c integration-mir
    - d: dmd-2.087.0
    - d: dmd-2.086.1
    - d: dmd-2.085.1
    - d: ldc-1.15.0
    - d: ldc-1.15.0
    - d: ldc-1.14.0
  allow_failures:
    - d: dmd-nightly


before_install:
  - curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
  - source /etc/lsb-release
  - echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
  - sudo apt-get update

install:
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install influxdb libevent-dev

before_script:
  - sudo service influxdb start

script:
  - dub test
  - dub run --build=unittest -c integration
  - dub build
