language: d
sudo: true
dist: bionic

matrix:
  include:
    - d: dmd-nightly
    - d: dmd
    - d: dmd-2.090.0
    - d: dmd-2.089.1
    - d: dmd-2.088.1
    - d: dmd-2.087.1
    - d: ldc
    - d: ldc-1.19.0
    - d: ldc-1.18.0
    - d: ldc-1.17.0
  allow_failures:
    - d: dmd-nightly


before_install:
  - curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
  - source /etc/lsb-release
  - echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
  - sudo apt-get update

install:
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install influxdb libevent-dev

before_script:
  - sudo service influxdb start

script:
  - dub test
  - dub run --root mir-integration-example
  - dub build
  - cd integration
  - dub run --build=unittest -c integration
  - dub run --build=unittest -c integration-mir
